# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

# Base image for both webserver and daemon
FROM python:3.10-slim AS base

RUN apt update && apt install gettext -y && apt autoclean  && \
    pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY start_dagster.bash dagster_config_source.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

RUN chmod +x start_dagster.bash

CMD ["./start_dagster.bash"]
