# Dagster libraries to run both dagster-webserver and the dagster-daemon. Does not
# need to have access to any pipeline code.

# Base image for both webserver and daemon
FROM python:3.10-slim AS base

RUN pip install \
    dagster \
    dagster-graphql \
    dagster-webserver \
    dagster-postgres

# Set $DAGSTER_HOME and copy dagster instance and workspace YAML there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY dagster.yaml workspace.yaml $DAGSTER_HOME

WORKDIR $DAGSTER_HOME

# Webserver image
FROM base AS webserver
CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "3000", "-w", "workspace.yaml"]

# Daemon image
FROM base AS daemon
CMD ["dagster-daemon", "run"]
